In [ ]:
import numpy as np


#### Print the numpy version and the configuration.


In [ ]:
# print numpy version
print(np.__version__)
print(np.show_config())


#### Initialise a vector that contains numbers from 1 to 20 and reverse it vector (first element becomes last).


In [ ]:
array = np.arange(1, 21)
reversed_array = np.flip(array)
print("Normal Array : ", array)
print("Reversed Array : ", reversed_array)

#### Create a 3x3 array with random values and find the minimum and maximum value.


In [ ]:
# Create a 3x3 array with random integers in the range 1-20
matrix = np.random.randint(1, 20, (3, 3))
print(matrix)

# Find the minimum and maximum value
min_val = matrix.min()
max_val = matrix.max()

print("Minimum value:", min_val)
print("Maximum value:", max_val)


#### Consider a (5,5,8) shape array, what is the index (x,y,z) of the 100th element?


In [ ]:
random_array = np.random.random((5, 5, 8))

# Docs mention the following:
# numpy.unravel_index(indices, shape, order='C')
index = np.unravel_index(99, random_array.shape)

print("Index of the 100th element:", index)

#### How to find common values between two arrays? Demonstrate.


We can use intersect1d() to find the common elements between two array <br>
Docs : <br>
`numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)`<br>
Find the intersection of two arrays. <br>
Return the sorted, unique values that are in both of the input arrays.


In [ ]:
#  We use the intersect1d() function to find the common elements between two arrays
array1 = np.random.randint(0, 10, 10)
array2 = np.random.randint(0, 10, 10)

print("Array 1:", array1)
print("Array 2:", array2)

common_elements = np.intersect1d(array1, array2)
print("Common elements:", common_elements)

#### Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.


In [24]:
# create a 10x2 numpy array with random cartesian coordinates
cartesian_coords = np.random.randint(1, 20, (10, 2))

# print the cartesian coordinates
print("Carteisan Coordinattes : \n", cartesian_coords)

# convert cartesian coordinates to polar coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

r = np.round(np.sqrt(x**2 + y**2), 2)
# theta = np.round(np.arctan2(y, x) * 180 / np.pi, 2)
theta = np.round(np.rad2deg(np.arctan2(y, x)), 2)

polar_coords = np.column_stack((r, theta))

# print the resulting polar coordinates
print("Polar Coordinated : \n", polar_coords)

Carteisan Coordinattes : 
 [[ 6  8]
 [16  7]
 [14 15]
 [ 9  9]
 [ 5 17]
 [ 6 13]
 [19 11]
 [ 2 10]
 [17 18]
 [10 12]]
Polar Coordinated : 
 [[10.   53.13]
 [17.46 23.63]
 [20.52 46.97]
 [12.73 45.  ]
 [17.72 73.61]
 [14.32 65.22]
 [21.95 30.07]
 [10.2  78.69]
 [24.76 46.64]
 [15.62 50.19]]


#### Demonstrate printing all the values of an array.

In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("Array : ", arr.reshape(1, arr.size))

Array :  [[ 1  2  3  4  5  6  7  8  9 10]]


#### How to convert a float (32 bits) array into an integer (32 bits) in place? Demonstrate using an example. [Use NumPy Datatypes]

In [25]:
# create a float32 numpy array
float_array = np.array([1.2, 2.3, 3.4], dtype=np.float32)

# convert the float32 array to an int32 array in place
int_array = float_array.astype(np.int32, copy=False)

# print the resulting int32 array
print(int_array)

[1 2 3]
