In [1]:
import numpy as np


#### Print the numpy version and the configuration.


In [2]:
# print numpy version
print(np.__version__)
print(np.show_config())


1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### Initialise a vector that contains numbers from 1 to 20 and reverse it vector (first element becomes last).


In [3]:
array = np.arange(1, 21)
reversed_array = np.flip(array)
print("Normal Array : ", array)
print("Reversed Array : ", reversed_array)

Normal Array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reversed Array :  [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


#### Create a 3x3 array with random values and find the minimum and maximum value.


In [4]:
# Create a 3x3 array with random integers in the range 1-20
matrix = np.random.randint(1, 20, (3, 3))
print(matrix)

# Find the minimum and maximum value
min_val = matrix.min()
max_val = matrix.max()

print("Minimum value:", min_val)
print("Maximum value:", max_val)


[[ 3 17  5]
 [ 4 10 14]
 [ 9  6  3]]
Minimum value: 3
Maximum value: 17


#### Consider a (5,5,8) shape array, what is the index (x,y,z) of the 100th element?


In [5]:
random_array = np.random.random((5, 5, 8))

# Docs mention the following:
# numpy.unravel_index(indices, shape, order='C')
index = np.unravel_index(99, random_array.shape)

print("Index of the 100th element:", index)

Index of the 100th element: (2, 2, 3)


#### How to find common values between two arrays? Demonstrate.


We can use intersect1d() to find the common elements between two array <br>
Docs : <br>
`numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)`<br>
Find the intersection of two arrays. <br>
Return the sorted, unique values that are in both of the input arrays.


In [10]:
#  We use the intersect1d() function to find the common elements between two arrays
array1 = np.random.randint(0, 11, 10)
array2 = np.random.randint(0, 11, 10)

print("Array 1:", array1)
print("Array 2:", array2)

common_elements = np.intersect1d(array1, array2)
print("Common elements:", common_elements)

Array 1: [ 1 10  8  7  7  4  8  8  1  1]
Array 2: [ 2  7  6  9  1  4  9  2 10  5]
Common elements: [ 1  4  7 10]


#### Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.


In [7]:
# create a 10x2 numpy array with random cartesian coordinates
cartesian_coords = np.random.randint(1, 20, (10, 2))

# print the cartesian coordinates
print("Carteisan Coordinattes : \n", cartesian_coords)

# convert cartesian coordinates to polar coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

r = np.round(np.sqrt(x**2 + y**2), 2)
# theta = np.round(np.arctan2(y, x) * 180 / np.pi, 2)
theta = np.round(np.rad2deg(np.arctan2(y, x)), 2)

polar_coords = np.column_stack((r, theta))

# print the resulting polar coordinates
print("Polar Coordinated : \n", polar_coords)

Carteisan Coordinattes : 
 [[11 16]
 [ 5 17]
 [16 14]
 [11  2]
 [14 16]
 [ 1 16]
 [11  8]
 [13  6]
 [ 9  2]
 [18 13]]
Polar Coordinated : 
 [[19.42 55.49]
 [17.72 73.61]
 [21.26 41.19]
 [11.18 10.3 ]
 [21.26 48.81]
 [16.03 86.42]
 [13.6  36.03]
 [14.32 24.78]
 [ 9.22 12.53]
 [22.2  35.84]]


#### Demonstrate printing all the values of an array.

In [8]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("Array : ", arr.reshape(1, arr.size))

Array :  [[ 1  2  3  4  5  6  7  8  9 10]]


#### How to convert a float (32 bits) array into an integer (32 bits) in place? Demonstrate using an example. [Use NumPy Datatypes]

In [9]:
# create a float32 numpy array
float_array = np.array([1.2, 2.3, 3.4], dtype=np.float32)

# convert the float32 array to an int32 array in place
int_array = float_array.astype(np.int32, copy=False)

# print the resulting int32 array
print(int_array)

[1 2 3]
